# Generated by Django 4.1 on 2023-04-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0005_company_details_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_details',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='image/profile'),
        ),
    ]
