# Generated by Django 4.1 on 2023-04-19 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0006_alter_company_details_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_details',
            name='pincode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
