# Generated by Django 3.2.20 on 2023-09-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0006_auto_20230906_0708'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_credits_bills_items_bills',
            name='account',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
