# Generated by Django 3.2.20 on 2023-09-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0007_vendor_credits_bills_items_bills_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banking',
            name='bd_bnk_det',
            field=models.CharField(blank=True, default='', max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='banking',
            name='mail_addr',
            field=models.CharField(blank=True, default='', max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='banking',
            name='opening_bal',
            field=models.CharField(blank=True, default='', max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='payment_made',
            name='cash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
