# Generated by Django 4.1 on 2023-05-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0008_additem_purchase_sales_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_details',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company_details',
            name='gst_num',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company_details',
            name='pan_num',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company_details',
            name='pincode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company_details',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='image/profile'),
        ),
    ]
