# Generated by Django 3.2.20 on 2023-09-13 05:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zohoapp', '0008_auto_20230911_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='EWayBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.CharField(max_length=50, null=True)),
                ('transsub', models.CharField(max_length=50, null=True)),
                ('customerzz', models.CharField(max_length=100, null=True)),
                ('cemail', models.EmailField(max_length=255, null=True)),
                ('cgst_trt_inp', models.CharField(max_length=100, null=True)),
                ('cgstin_inp', models.CharField(max_length=100, null=True)),
                ('invoiceno', models.CharField(max_length=50, null=True)),
                ('date', models.DateField()),
                ('trans', models.CharField(max_length=100, null=True)),
                ('adda', models.TextField(max_length=255, null=True)),
                ('addb', models.TextField(max_length=255, null=True)),
                ('srcofsupply', models.CharField(max_length=100, null=True)),
                ('transportation', models.CharField(max_length=100, null=True)),
                ('km', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('vno', models.CharField(max_length=50, null=True)),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('sgst', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('cgst', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('igst', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('shipping_charge', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('adj', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('note', models.TextField(max_length=255, null=True)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('cust', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zohoapp.customer')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EWayBillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('eway_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zohoapp.ewaybill')),
            ],
        ),
    ]
